#welcome to new age astrology......here i would be deciding the fate of people on TITANIC

#Having a well defined problem statement is very important in pursuing a ML project.It helps us
#to stay in a course rather than drifting away in this vast ocean of ML field

#defining problem statement

#==============================================================================
# Here data is already divided into Train and Test data.and we have to build a model to predict
# the survivial probability of passengers. How do i quantify my success. let us say my model
# is flipping a coin,that would predict the survival probability with 0.5 probability.so after
# all these efforts it would be only fair if the survival porbability would be more than 0.5.
# to make myself more happy i am considering it to be 0.7
#------------------------------------------------------------------------------
#Final Problem Statement
#------------------------------------------------------------------------------
#
#preapre a model using train data and that would predict the survival prediction with 70% 
#sucessrate
# 
#==============================================================================

#importing dataframe libs

In [3]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import matplotlib as plot
import seaborn as sns

#reading working data files

In [6]:
train_df = pd.read_csv("D:/Syam/Epiphany/DataSets/Titanic/train.csv")
test_df = pd.read_csv("D:/Syam/Epiphany/DataSets/Titanic/test.csv")

In [7]:
train_df.shape

(891, 12)

In [8]:
test_df.shape

(418, 11)

In [9]:
train_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [10]:
test_df.count()

PassengerId    418
Pclass         418
Name           418
Sex            418
Age            332
SibSp          418
Parch          418
Ticket         418
Fare           417
Cabin           91
Embarked       418
dtype: int64

In [11]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [12]:
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

#key observation is missingvalues are present in data like in Cabin
#note that its not possible to implement ML algorithms if there are missing values

In [14]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [15]:
train_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [16]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [17]:
test_df.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

#out of all numeric features Age has missing values

In [20]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

#embarked and age is also having missing values in train data
#cabin and age features have missing values.

In [23]:
train_df["Embarked"].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

#filling embarked missing values with mode which is S which is basically mode for Embarked

In [25]:
train_df["Embarked"] = train_df["Embarked"].fillna("S")

In [26]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [27]:
train_df['Age'] = train_df.groupby('Sex').Age.transform(lambda x: x.fillna(x.mean()))
test_df['Age'] = test_df.groupby('Sex').Age.transform(lambda x: x.fillna(x.mean()))

test_df['Fare'] = test_df['Fare'].fillna(test_df['Fare'].mean())

In [28]:
train_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [29]:
test_df.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [30]:
map_sex = {'male' : 0, 'female' : 1}
map_embark = {'S' : 0, 'C' : 1, 'Q' : 2}

In [31]:
train_df['Sex'] = train_df['Sex'].map(map_sex)
train_df['Embarked'] = train_df['Embarked'].map(map_embark)
test_df['Sex'] = test_df['Sex'].map(map_sex)
test_df['Embarked'] = test_df['Embarked'].map(map_embark)

In [32]:
train_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         0  
1          PC 17599  71.2833   C85         1  
2  STON/O2. 3101282   7.9250   NaN         0

In [33]:
test_df.head(3)

PassengerId  Pclass                              Name  Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    0  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)    1  47.0      1   
2          894       2         Myles, Mr. Thomas Francis    0  62.0      0   

   Parch  Ticket    Fare Cabin  Embarked  
0      0  330911  7.8292   NaN         2  
1      0  363272  7.0000   NaN         0  
2      0  240276  9.6875   NaN         2

In [ ]:
# Removing features like PassengerId, Name, Ticket, Cabin

In [34]:
train_df1 = train_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)
test_df1 = test_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)

In [35]:
train_df1.head(3)

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         0
1         1       1    1  38.0      1      0  71.2833         1
2         1       3    1  26.0      0      0   7.9250         0

In [36]:
test_df1.head(3)

Pclass  Sex   Age  SibSp  Parch    Fare  Embarked
0       3    0  34.5      0      0  7.8292         2
1       3    1  47.0      1      0  7.0000         0
2       2    0  62.0      0      0  9.6875         2

In [37]:
a = train_df1.iloc[:,1:7].values
b = train_df1.iloc[:,0].values
c = test_df1.iloc[:,0:6].values 

In [38]:
# regularization of features.

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
std = StandardScaler()
a_t= std.fit_transform(a)
c_t = std.transform(c)

In [41]:
#ML libraries

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [43]:
Logistic = LogisticRegression()
Logistic.fit(a_t, b)
Logistic_train_predict = Logistic.predict(a_t)
Logistic_predicted = Logistic.predict(c_t)
print('---logistic regression---') 
print(metrics.accuracy_score(Logistic_train_predict, b))
print("confusion matric")
print("{0}".format(metrics.confusion_matrix(b, Logistic_train_predict, labels = [1,0])))
print("")
print("classification report")
print("{0}".format(metrics.classification_report(b, Logistic_train_predict, labels = [1,0])))
print("-----------")

---logistic regression---
0.79797979798
confusion matric
[[239 103]
 [ 77 472]]

classification report
             precision    recall  f1-score   support

          1       0.76      0.70      0.73       342
          0       0.82      0.86      0.84       549

avg / total       0.80      0.80      0.80       891

-----------


In [44]:
naive = GaussianNB()
naive.fit(a_t, b)
naive_train_predict = naive.predict(a_t)
naive_test_predict = naive.predict(c_t)
print('---Naive Bayes-------')
print(metrics.accuracy_score(naive_train_predict, b))
print("confusion matric")
print("{0}".format(metrics.confusion_matrix(b, naive_train_predict, labels = [1,0])))
print("")
print("classification report")
print("{0}".format(metrics.classification_report(b, naive_train_predict, labels = [1,0])))
print('------------')

---Naive Bayes-------
0.792368125701
confusion matric
[[241 101]
 [ 84 465]]

classification report
             precision    recall  f1-score   support

          1       0.74      0.70      0.72       342
          0       0.82      0.85      0.83       549

avg / total       0.79      0.79      0.79       891

------------


In [45]:
knn = KNeighborsClassifier()
knn.fit(a_t, b)
knn_train_predict = knn.predict(a_t)
knn_test_predict = knn.predict(c_t)
print('--------knn-------')
print(knn.score(a_t,b))
print(metrics.accuracy_score(knn_train_predict, b))
print("confusion matric")
print("{0}".format(metrics.confusion_matrix(b, knn_train_predict, labels = [1,0])))
print("")
print("classification report")
print("{0}".format(metrics.classification_report(b, knn_train_predict, labels = [1,0])))
print('------------')

--------knn-------
0.861952861953
0.861952861953
confusion matric
[[275  67]
 [ 56 493]]

classification report
             precision    recall  f1-score   support

          1       0.83      0.80      0.82       342
          0       0.88      0.90      0.89       549

avg / total       0.86      0.86      0.86       891

------------


In [46]:
randomforest = RandomForestClassifier()
randomforest.fit(a_t, b)
randomforest_train_predict = randomforest.predict(a_t)
randomforest_test_predict = randomforest.predict(c_t)
print('--------random forest-------')
print(metrics.accuracy_score(randomforest_train_predict, b))
print("confusion matric")
print("{0}".format(metrics.confusion_matrix(b, randomforest_train_predict, labels = [1,0])))
print("")
print("classification report")
print("{0}".format(metrics.classification_report(b, randomforest_train_predict, labels = [1,0])))
print('------------')

--------random forest-------
0.967452300786
confusion matric
[[323  19]
 [ 10 539]]

classification report
             precision    recall  f1-score   support

          1       0.97      0.94      0.96       342
          0       0.97      0.98      0.97       549

avg / total       0.97      0.97      0.97       891

------------


# of four algorithms RandomForests performs better on training data. higher accuracy on training data doesnt imply better model as it can be clear case of overfitting where models performs better on training data but couldnt perform when given new data.